/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#004d3d',
        'surface-variant': '#1e1e30',
        'surface-container-highest': '#28283e',
        'surface-dim': '#0f0f1a',
        'secondary-fixed': '#c0fff4',
        'primary': '#ff2d78',
        'error': '#ff4444',
        'on-secondary-fixed-variant': '#004d4d',
        'on-background': '#e8e0f0',
        'on-tertiary-container': '#fff0c0',
        'on-primary': '#1a0010',
        'surface-bright': '#1a1a2e',
        'surface-tint': '#ff2d78',
        'on-tertiary-fixed-variant': '#665200',
        'on-tertiary-fixed': '#1a1000',
        'surface': '#0f0f1a',
        'tertiary-container': '#665200',
        'background': '#0a0a12',
        'error-container': '#3d0f0f',
        'secondary-fixed-dim': '#00e6b8',
        'primary-fixed-dim': '#ff80aa',
        'on-secondary-fixed': '#001a1a',
        'tertiary': '#ffe04a',
        'tertiary-fixed-dim': '#ffe04a',
        'primary-fixed': '#ffe0ec',
        'on-primary-fixed-variant': '#8c0038',
        'surface-container': '#141422',
        'on-primary-fixed': '#3d0020',
        'secondary': '#00ffcc',
        'on-tertiary': '#1a1000',
        'outline': '#5a5068',
        'inverse-primary': '#8c0038',
        'surface-container-lowest': '#0a0a12',
        'primary-container': '#b3004e',
        'inverse-on-surface': '#0a0a12',
        'on-secondary-container': '#c0fff4',
        'on-surface-variant': '#a098b0',
        'on-secondary': '#001a1a',
        'tertiary-fixed': '#fff0c0',
        'outline-variant': '#302840',
        'surface-container-low': '#111118',
        'on-surface': '#e8e0f0',
        'on-primary-container': '#ffe0ec',
        'surface-container-high': '#1e1e30',
        'on-error-container': '#ffa0a0',
        'inverse-surface': '#e8e0f0',
        'on-error': '#1a0000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
}
